### ISSUE TITLE
Make the initial frontend build more flexible

### ISSUE THREAD

**Issue by dan-gamble** [onespacemedia/developer-automation#1]
For refence onespacemedia/server-management#26

**Comment by dan-gamble** [comment]
Closed because it was posted in the wrong repo, right repo: onespacemedia/project-template#9

**Comment by DanGamble89** [comment]
Closed because it was posted in the wrong repo, right repo: onespacemedia/project-template#9

**Comment by danielsamuels** [comment]
test

**Comment by lewiscollard** [comment]
didn't work
